---
title: "Asgn6_Miami"
author: "Alex Cardelle"
date: "10/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Miami Introduction Text
<http://rmarkdown.rstudio.com>.

**Knit** 

```{r library, eval=TRUE, echo=FALSE}
library(leaflet)
library(sf)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)
library(tidytransit)
```

```{r test boston black, eval=FALSE, echo=FALSE}
acs_vars <- load_variables(2019, "acs1")

```

``` {r ACS gay married map, eval=TRUE, echo=FALSE}

#load the variable

gay_hh <- get_acs(geography = "county",
                    year = 2019, survey = "acs5",
                    variables = c(tot_het_ma = "B09019_010",tot_het_um = "B09019_012", tot_gay_ma = "B09019_011", tot_gay_um = "B09019_013"),
                    output = "wide", geometry = TRUE) 

#mutate the data to eliminate of the margin of error

gay_hh <- gay_hh %>%
  select(-tot_het_maM, -tot_het_umM, -tot_gay_maM, -tot_gay_umM) %>%
  filter(tot_het_maE > 0) %>%
  mutate(pct_gay = round(100 * (tot_gay_maE + tot_gay_umE) / (tot_het_maE + tot_het_umE), 1))

#define the palette
household_palette <- colorNumeric(c("lightblue", "darkblue"),
                                gay_hh$pct_gay)
#plot the map
gay_map <-
  leaflet(gay_hh) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(fillColor = ~household_palette(pct_gay), weight = 1, color = "gray", fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "yellow", fillOpacity = 0.9),
              label = gay_hh$NAME,
              popup = paste("Total population in coupled households: ", (gay_hh$tot_het_maE+gay_hh$tot_het_umE+gay_hh$tot_gay_maE+gay_hh$tot_gay_umE), "<br/>",
                            "Total population in coupled same-sex households: ", (gay_hh$tot_gay_maE+gay_hh$tot_gay_umE), " (", 
                            gay_hh$pct_gay, "%)", sep = "")) %>%
    addLegend("bottomright", pal = household_palette, values = ~pct_gay,
    title = "Percent of population living in<br/>same-sex households",
    labFormat = labelFormat(suffix = "%"),
    opacity = 1)

gay_map
```